### ISSUE TITLE
Not compatible with the version of your running IDE

### ISSUE THREAD

**Issue by Thebluedragon7** [HMYDK/AIGitCommit#1]
The plugin is not compatible with Jetbrains IDE **2024.2**.

IDE:  *WebStorm 2024.2*

![image](https://github.com/user-attachments/assets/369b4b9e-f598-434a-a318-9f460cfe90ce)

**Comment by HMYDK** [comment]
thanks for your report . i will fix it later . 😊

**Comment by HMYDK** [comment]
Please try the new version (v0.0.5) @Thebluedragon7

**Comment by Thebluedragon7** [comment]
> Please try the new version (v0.0.5) @Thebluedragon7

It's working again, thanks!

**Comment by Thebluedragon7** [comment]
The plugin is not compatible with Jetbrains IDE 2024.3

IDE: _WebStorm 2024.3_

![image](https://github.com/user-attachments/assets/1dddbfb8-3279-4c5d-b468-5e656065d1a5)

**Comment by HMYDK** [comment]
the new version has been released. 
please try again . @Thebluedragon7
